
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar  from "@/components/Navbar";
import PharmacyCard from "@/components/PharmacyCard";
import HomeServices from "@/components/HomeServices";
import FreeMedicalAdvice from "@/components/Freemedicaladvice ";
import SymptomsAndDiseases from "@/components/Symptomsanddiseases";
import TopArticles from "@/components/Toparticles";
import CustomerReviews from "@/components/Customerreviews";
import WhyChooseUs from "@/components/Whychooseus";
import DoctorCTA from "@/components/Doctorapp";
import DownloadApp from "@/components/Downloadapp";
import FAQ from "@/components/Faq ";
import DoctorsByCity from '@/components/Doctorsbycity';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        {children}
        <Navbar />
              <PharmacyCard />
              <HomeServices />
              <FreeMedicalAdvice />
              <SymptomsAndDiseases />
              <TopArticles />
              <CustomerReviews />
              <WhyChooseUs />
              <DoctorCTA />
              <DownloadApp />
              <FAQ />
              <DoctorsByCity />

      </body>
    </html>
  );
}
